"""
Seed demo data into a demo.db and write .env.local for Next.js.
Run: python scripts/seed_demo.py
"""
import asyncio, uuid, sys, os, pathlib
from datetime import datetime, timezone, timedelta
import aiosqlite
sys.path.insert(0, str(pathlib.Path(__file__).parent.parent.parent / "agentsave-dashboard"))

from agentsave_dashboard.database import init_db
from agentsave_dashboard.auth import generate_api_token, hash_token, create_jwt

DB_PATH = str(pathlib.Path(__file__).parent.parent.parent / "agentsave-dashboard" / "demo.db")
ENV_PATH = str(pathlib.Path(__file__).parent.parent / ".env.local")

DEMO_EVENTS = [
    # (framework, model, tokens_before, tokens_after, task_success, days_ago)
    *[("langchain",  "gpt-4o",              10000, 7000,  True,  i) for i in range(10)],
    *[("autogen",    "claude-sonnet-4-6",    8000,  5600,  True,  i) for i in range(5)],
    *[("crewai",     "gpt-4o",              12000, 8400,  True,  i) for i in range(4)],
    *[("smolagents", "gemini-2-flash",       6000,  4200,  True,  i) for i in range(4)],
    *[("langgraph",  "claude-sonnet-4-6",    9000,  6300,  False, i) for i in range(3)],
    *[("raw",        "llama-3.1-8b",         5000,  3500,  True,  i) for i in range(4)],
]

async def seed():
    if os.path.exists(DB_PATH):
        os.remove(DB_PATH)
    async with aiosqlite.connect(DB_PATH) as db:
        db.row_factory = aiosqlite.Row
        await db.execute("PRAGMA foreign_keys = ON")
        await init_db(db)

        now = datetime.now(timezone.utc)
        user_id = str(uuid.uuid4())
        project_id = str(uuid.uuid4())
        raw_token, token_hash = generate_api_token()

        await db.execute(
            "INSERT INTO users (id, email, stripe_customer_id, tier, created_at) VALUES (?,?,?,?,?)",
            (user_id, "demo@agentsave.io", None, "pro", now.isoformat()),
        )
        await db.execute(
            "INSERT INTO projects (id, user_id, name, created_at) VALUES (?,?,?,?)",
            (project_id, user_id, "Demo Project", now.isoformat()),
        )
        await db.execute(
            "INSERT INTO api_tokens (id, user_id, project_id, token_hash, name, created_at) VALUES (?,?,?,?,?,?)",
            (str(uuid.uuid4()), user_id, project_id, token_hash, "demo-token", now.isoformat()),
        )

        for fw, model, tb, ta, success, days in DEMO_EVENTS:
            ts = (now - timedelta(days=days)).isoformat()
            await db.execute(
                "INSERT INTO events (id, project_id, run_id, framework, model_name, "
                "tokens_before, tokens_after, iterations_total, iterations_saved, task_success, timestamp) "
                "VALUES (?,?,?,?,?,?,?,?,?,?,?)",
                (str(uuid.uuid4()), project_id, str(uuid.uuid4()), fw, model,
                 tb, ta, 5, 2, 1 if success else 0, ts),
            )
        await db.commit()

        jwt_token = create_jwt(user_id, "demo@agentsave.io", "pro")

        # Write .env.local
        env_content = f"""# Auto-generated by seed_demo.py - do not commit
DASHBOARD_API_URL=http://localhost:8000
DEMO_PROJECT_ID={project_id}
DEMO_JWT={jwt_token}
DEMO_API_TOKEN={raw_token}
"""
        with open(ENV_PATH, "w") as f:
            f.write(env_content)

        # Print summary
        total_saved = sum(tb - ta for _, _, tb, ta, _, _ in DEMO_EVENTS)
        success_count = sum(1 for _, _, _, _, s, _ in DEMO_EVENTS if s)
        print(f"OK Seeded {len(DEMO_EVENTS)} events into {DB_PATH}")
        print(f"  Frameworks: langchain(10) autogen(5) crewai(4) smolagents(4) langgraph(3) raw(4)")
        print(f"  Tokens saved: {total_saved:,}")
        print(f"  Cost saved: ${total_saved * 0.000003:.4f}")
        print(f"  Success rate: {success_count/len(DEMO_EVENTS):.1%}")
        print(f"  Project ID: {project_id}")
        print(f"OK Written .env.local to {ENV_PATH}")
        return project_id, jwt_token, total_saved, success_count

asyncio.run(seed())
